In [ ]:
from google.colab import drive
drive.mount("/content/drive")

In [ ]:
# import libraries
import pandas as pd
import numpy as np
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Load the Iris dataset
path="/content/drive/MyDrive/Dataset/Iris.csv"
df = pd.read_csv(path, delimiter=';', header=None)
df.head(5)

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [ ]:
# Extract the input features and target variable
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
# Normalize the input values using max-min normalization
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)
print(X_normalized[:10])

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]]


In [ ]:
print(df.iloc[:, -1].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [ ]:
encoder = OneHotEncoder()

y_encoded=  encoder.fit_transform(df.iloc[:, -1:].values).toarray()
print(y_encoded[:10])
#y_encoded_df = pd.DataFrame(y_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
# Convert the normalized data and encoded features to DataFrames
X_normalized_df = pd.DataFrame(X_normalized)
y_encoded_df = pd.DataFrame(y_encoded)

# Concatenate the normalized data and encoded features horizontally
df1 = pd.concat([X_normalized_df, y_encoded_df], axis=1)

# Print the merged data
print(df1)

            0         1         2         3    0    1    2
0    0.222222  0.625000  0.067797  0.041667  1.0  0.0  0.0
1    0.166667  0.416667  0.067797  0.041667  1.0  0.0  0.0
2    0.111111  0.500000  0.050847  0.041667  1.0  0.0  0.0
3    0.083333  0.458333  0.084746  0.041667  1.0  0.0  0.0
4    0.194444  0.666667  0.067797  0.041667  1.0  0.0  0.0
..        ...       ...       ...       ...  ...  ...  ...
145  0.666667  0.416667  0.711864  0.916667  0.0  0.0  1.0
146  0.555556  0.208333  0.677966  0.750000  0.0  0.0  1.0
147  0.611111  0.416667  0.711864  0.791667  0.0  0.0  1.0
148  0.527778  0.583333  0.745763  0.916667  0.0  0.0  1.0
149  0.444444  0.416667  0.694915  0.708333  0.0  0.0  1.0

[150 rows x 7 columns]


In [ ]:
df1=df1.iloc[np.random.permutation(len(df1))]
print(df1.head(10))

            0         1         2         3    0    1    2
120  0.722222  0.500000  0.796610  0.916667  0.0  0.0  1.0
89   0.333333  0.208333  0.508475  0.500000  0.0  1.0  0.0
43   0.194444  0.625000  0.101695  0.208333  1.0  0.0  0.0
57   0.166667  0.166667  0.389831  0.375000  0.0  1.0  0.0
69   0.361111  0.208333  0.491525  0.416667  0.0  1.0  0.0
37   0.166667  0.458333  0.084746  0.000000  1.0  0.0  0.0
23   0.222222  0.541667  0.118644  0.166667  1.0  0.0  0.0
141  0.722222  0.458333  0.694915  0.916667  0.0  0.0  1.0
3    0.083333  0.458333  0.084746  0.041667  1.0  0.0  0.0
123  0.555556  0.291667  0.661017  0.708333  0.0  0.0  1.0


In [ ]:
#print(df1.iloc[:, -1].unique())

[1. 0.]


In [ ]:
# Split the dataset into training/validation/test sets
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y_encoded, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(X_val.shape)

(96, 4)
(30, 4)
(24, 4)


In [ ]:
# Construct the neural network
#Neural network module
# Construct the neural network
model = Sequential()
model.add(Dense(20, activation='relu', input_shape=(4,)))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
# Train the neural network on the prepared Iris dataset
epochs = 4
for epoch in range(epochs):
    history = model.fit(X_train, y_train, validation_data=(X_val, y_val), batch_size=10, epochs=1, verbose=0)
    train_loss = history.history['loss'][0]
    val_loss = history.history['val_loss'][0]
    print(f"Epoch {epoch+1}/{epochs} - Training Loss: {train_loss:.4f} - Validation Loss: {val_loss:.4f}")

# Evaluate the model on the test set
test_loss = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss:.4f}")


Epoch 1/100 - Training Loss: 0.1680 - Validation Loss: 0.1910
Epoch 2/100 - Training Loss: 0.1654 - Validation Loss: 0.1894
Epoch 3/100 - Training Loss: 0.1628 - Validation Loss: 0.1870
Epoch 4/100 - Training Loss: 0.1601 - Validation Loss: 0.1849
Epoch 5/100 - Training Loss: 0.1573 - Validation Loss: 0.1822
Epoch 6/100 - Training Loss: 0.1548 - Validation Loss: 0.1797
Epoch 7/100 - Training Loss: 0.1520 - Validation Loss: 0.1779
Epoch 8/100 - Training Loss: 0.1494 - Validation Loss: 0.1756
Epoch 9/100 - Training Loss: 0.1468 - Validation Loss: 0.1729
Epoch 10/100 - Training Loss: 0.1443 - Validation Loss: 0.1712
Epoch 11/100 - Training Loss: 0.1418 - Validation Loss: 0.1689
Epoch 12/100 - Training Loss: 0.1393 - Validation Loss: 0.1669
Epoch 13/100 - Training Loss: 0.1369 - Validation Loss: 0.1644
Epoch 14/100 - Training Loss: 0.1348 - Validation Loss: 0.1616
Epoch 15/100 - Training Loss: 0.1326 - Validation Loss: 0.1593
Epoch 16/100 - Training Loss: 0.1305 - Validation Loss: 0.1577
E

In [ ]:
# Calculate accuracy on the test set
y_pred = model.predict(X_test)
y_pred_encoded = np.argmax(y_pred, axis=1)
y_test_encoded = np.argmax(y_test, axis=1)
accuracy = np.mean(y_pred_encoded == y_test_encoded)
print(f"Test Accuracy: {accuracy*100:.2f}%")

1/1 [==============================] - 0s 21ms/step
Test Accuracy: 93.33%
